import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import "./globals.css";

const RobotoFont = Roboto({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jira-Sync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/favicon.png" type="image/png" />
      <body className={`${RobotoFont.className}`}>
        {children}
      </body>
    </html>
  );
}

